
spring:
  application:
    name: student-attendance-system         # 应用名称

  thymeleaf:                            # THYMELEAF (ThymeleafAutoConfiguration)
    cache: true                         # 开启模板缓存（默认值： true ）
    check-template: true                # 检查模板是否存在，然后再呈现
    check-template-location: true       # 检查模板位置是否正确（默认值 :true ）
    content-type: text/html             #Content-Type 的值（默认值： text/html ）
    enabled: true                       # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8                     # 模板编码
    mode: HTML                          # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    excluded-view-names:                # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    prefix: classpath:/templates/       # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    suffix: .ftl                        # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                     # 数据库驱动
    name: student_attendance_system                                 # 数据源名称
    url: jdbc:mysql://localhost:3306/student_attendance_system?serverTimezone=UTC  # 数据库连接地址
    username: root               # 数据库用户名&密码：
    password: root

  freemarker:
    template-loader-path: classpath:/templates/                     # freemarker模板加载路径
    enabled: true
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html

server:
  port: 8080

#下面这些内容是为了让MyBatis映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.studentattendancesystem.model #指定Mybatis的实体目录




